# ?? ???? (?? ?? ??)
spring.profiles.active=dev

# ?? ??
spring.application.name=synergyhub

# H2 ?? (??)
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true

# JPA ?? ??
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true

#hibernate logging
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.SQL=debug

#swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


